server:
  port: 9088

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queues:
  name:
    test: test-queue

logging:
  level:
    org.springframework.boot.autoconfigure.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG